package com.dengpinbo.novelhelper;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.novelhelper.greendaobeans.describe.MannerDescribe;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MANNER_DESCRIBE".
*/
public class MannerDescribeDao extends AbstractDao<MannerDescribe, Long> {

    public static final String TABLENAME = "MANNER_DESCRIBE";

    /**
     * Properties of entity MannerDescribe.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PartName = new Property(1, String.class, "partName", false, "PART_NAME");
        public final static Property Meaning = new Property(2, String.class, "meaning", false, "MEANING");
    }


    public MannerDescribeDao(DaoConfig config) {
        super(config);
    }
    
    public MannerDescribeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MANNER_DESCRIBE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PART_NAME\" TEXT," + // 1: partName
                "\"MEANING\" TEXT);"); // 2: meaning
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MANNER_DESCRIBE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MannerDescribe entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String partName = entity.getPartName();
        if (partName != null) {
            stmt.bindString(2, partName);
        }
 
        String meaning = entity.getMeaning();
        if (meaning != null) {
            stmt.bindString(3, meaning);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MannerDescribe entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String partName = entity.getPartName();
        if (partName != null) {
            stmt.bindString(2, partName);
        }
 
        String meaning = entity.getMeaning();
        if (meaning != null) {
            stmt.bindString(3, meaning);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MannerDescribe readEntity(Cursor cursor, int offset) {
        MannerDescribe entity = new MannerDescribe( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // partName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // meaning
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MannerDescribe entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPartName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMeaning(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MannerDescribe entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MannerDescribe entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MannerDescribe entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
